# This script reads in abundance.tsv files generated by Kallisto, extracts the est_counts column from each, collates them 
# into a data frame, and writes out that data frame. The resulting geneExpressionCounts.txt is intended for analysis with
# BioJupies https://amp.pharm.mssm.edu/biojupies/

# The script requires two arguments:
#   1. The path to the directories containing the subdirectories that hold the abundance.tsv files;
#   2. The path to where you want to output geneExpressionCounts.txt (if this is the present working directory set this
#     argument to ".").

args <- commandArgs(trailingOnly = TRUE)
path <- args[1]
samples <- list.files(path)
for(i in 1:length(samples)){
  to.read <- samples[i]
  full.path <- paste(path,to.read,"abundance.tsv",sep="/")
  abundance <- read.table(full.path,head=T,stringsAsFactors = F)
  assign(to.read,abundance)
}
target_id <- abundance$target_id
gene.symbols <- sapply(target_id, function(x) strsplit(x,split="\\|")[[1]][6])
unique.genes <- unique(gene.symbols)
unique.genes <- na.omit(unique.genes)
gene.expression.counts <- array(NA,dim=c(length(unique.genes),length(samples)))
rownames(gene.expression.counts) <- unique.genes
colnames(gene.expression.counts) <- samples
for(i in 1:length(samples)){
  to.aggregate <- samples[i]
  abundance <- get(to.aggregate)
  est.counts <- abundance$est_counts
  aggregate.counts <- aggregate(est.counts,by=list(gene.symbols),FUN="sum")
  gene.expression.counts[,i] <- aggregate.counts[,2]
}
gene.expression.counts <- cbind.data.frame(Genes=unique.genes,gene.expression.counts)
out.path <- paste(args[2],"geneExpressionCounts.txt",sep="/")
write.table(gene.expression.counts,out.path,sep="\t",quote=F,row.names=F)
